import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'overbed-tables', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'vaunn-overbed-table-walnut', name: 'Vaunn Medical Adjustable Overbed Table (Walnut)', brand: 'Vaunn', sub: 'rolling', q: 'Vaunn medical adjustable overbed table walnut rolling', badge: 'Best Overall', price: 69.99, rating: 4.6, reviews: 28974, desc: 'The hospital-and-home favorite: a 30"×15" walnut top with spring-loaded infinite height adjustment and an H-base that rolls under most beds and wheelchairs.', features: ['30"×15" walnut laminate top', 'Spring-loaded height 28.5"–40.5"', 'H-style base + 2" locking casters', 'Chrome-plated steel, 45 lb capacity'], pros: ['Trusted hospital design', 'Smooth infinite height adjust', 'Stable H-base rolls under beds'], cons: ['45 lb top capacity'], bestFor: ['eating in bed', 'recovery at home', 'wheelchair users'], specs: { top: '30×15 in', height: '28.5–40.5 in', base: 'H-style', capacity: '45 lb' } }),
  mk({ id: 'vaunn-overbed-table-black', name: 'Vaunn Medical Adjustable Overbed Table (Black)', brand: 'Vaunn', sub: 'rolling', q: 'Vaunn medical adjustable overbed table black rolling', badge: 'Best in Black', price: 66.49, rating: 4.6, reviews: 28974, desc: 'The same trusted Vaunn table in sleek black, with a textured anti-slip surface, welded tubular steel, and locking wheels at wheelchair-friendly height.', features: ['Textured anti-slip top', 'Chrome-plated welded tubular steel', 'Spring-loaded height adjust', 'Locking wheels, wheelchair-compatible'], pros: ['Modern black finish', 'Anti-slip surface', 'Same reliable Vaunn build'], cons: ['45 lb top capacity'], bestFor: ['modern bedrooms', 'wheelchair height', 'recovery'], specs: { top: '30×15 in', height: '28.5–40.5 in', base: 'H-style', finish: 'Black' } }),
  mk({ id: 'medical-king-overbed-table', name: 'Medical King Adjustable Overbed Table', brand: 'Medical King', sub: 'rolling', q: 'Medical King adjustable overbed bedside table 200 lb', badge: 'Strongest Top', price: 59.99, rating: 4.6, reviews: 918, desc: 'A dark-walnut aluminum-and-wood table with a heavy 200 lb top capacity and spring-loaded height adjustment — built for seniors and patients.', features: ['Dark walnut aluminum + wood top (30"×15.5")', 'Spring-loaded height 28.5"–40.5"', '200 lb top capacity', 'Smooth rolling wheels'], pros: ['Very high top capacity', 'Sturdy aluminum frame', 'Roomy surface'], cons: ['Fewer reviews than Vaunn/Drive'], bestFor: ['heavier loads', 'seniors and patients', 'eating in bed'], specs: { top: '30×15.5 in', height: '28.5–40.5 in', capacity: '200 lb', frame: 'Aluminum' } }),
  mk({ id: 'sweetcrispy-overbed-table', name: 'Sweetcrispy Rolling Overbed Table with Tilt Top', brand: 'Sweetcrispy', sub: 'tilt', q: 'Sweetcrispy rolling overbed bedside table tilt top white', badge: 'Best Tilt-Top', price: 54.99, rating: 4.5, reviews: 745, desc: 'A modern white table with an adjustable, tilting top for reading or laptops, on four rolling wheels that fit over most standard beds.', features: ['Adjustable height + tilting top', 'Modern white, wipe-clean finish', '4 rolling wheels', '33 lb capacity'], pros: ['Tilt top eases neck strain', 'Clean modern look', 'Fits most beds'], cons: ['Lighter-duty than medical models'], bestFor: ['reading and tablets', 'laptops in bed', 'modern bedrooms'], specs: { top: 'Tilting', capacity: '33 lb', wheels: '4', finish: 'White' } }),
  mk({ id: 'tigerdad-overbed-table-king-queen', name: 'TigerDad Overbed Table for King/Queen Beds', brand: 'TigerDad', sub: 'adjustable-length', q: 'TigerDad overbed table king queen adjustable length 350 lb', badge: 'Best for Large Beds', price: 99.99, rating: 4.6, reviews: 2625, desc: 'A cross-bed table whose legs straddle the mattress, spanning 55"–83" in length and supporting 350 lb — the answer for queen and king beds.', features: ['Length spans 55"–83"', 'Height 25.6"–37.4"', '15 mm MDF top, 350 lb capacity', '1.5" locking casters'], pros: ['Fits queen and king beds', 'Very high capacity', 'Legs clear the mattress'], cons: ['Larger footprint to store'], bestFor: ['king/queen beds', 'heavier loads', 'couples'], specs: { length: '55–83 in', height: '25.6–37.4 in', capacity: '350 lb', top: '15 mm MDF' } }),
  mk({ id: 'arlopu-overbed-table-queen', name: 'Arlopu Queen-Size Overbed Table with 360° Wheels', brand: 'Arlopu', sub: 'adjustable-length', q: 'Arlopu queen size overbed table 360 wheels baffle 350 lb', badge: 'Biggest Surface', price: 84.00, rating: 4.6, reviews: 247, desc: 'An enormous 70.8"×16" cross-bed surface with a raised 3.9" baffle so items do not slide off, on four lockable 360° wheels for twin to queen beds.', features: ['Huge 70.8"×16" surface', '3.9" baffle prevents items falling', '350 lb capacity', '4 lockable 360° wheels'], pros: ['Massive work surface', 'Baffle keeps items in place', 'Fits up to queen beds'], cons: ['Newer listing, fewer reviews'], bestFor: ['large work surface', 'hobbies in bed', 'twin–queen beds'], specs: { top: '70.8×16 in', capacity: '350 lb', wheels: '360° lockable', baffle: '3.9 in' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} overbed-tables. Catalog now ${p.length} products.`);
