import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'door-wander-alarms', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'yistech-caregiver-door-alarm', name: 'YisTech Caregiver Door Alarm (3 Sensors + 2 Receivers)', brand: 'YisTech', sub: 'door-chime', q: 'YisTech caregiver pager door alarm dementia 3 sensor 2 receiver', badge: 'Best for Dementia', price: 35.99, rating: 4.5, reviews: 340, desc: 'Purpose-built for dementia monitoring: assign a different chime to each door so you instantly know which one opened, across a 260 ft range.', features: ['58 ringtones, 5 volume levels (0–110 dB)', 'Per-door chime ID + LED visual alert', '260 ft range, expandable to 20 sensors', 'Plug-in receivers + battery sensors'], pros: ['Tells you which door opened', 'Loud with visual alert', 'Multi-receiver coverage'], cons: ['Sensors use batteries'], bestFor: ['dementia care', 'multi-door homes', 'caregivers in another room'], specs: { type: 'Door chime', range: '260 ft', sensors: '3', receivers: '2' } }),
  mk({ id: 'metak-door-chime', name: 'METAK Wireless Door Open Chime Alarm', brand: 'METAK', sub: 'door-chime', q: 'METAK wireless door chime alarm open contact sensor', badge: 'Best Single-Door', price: 15.99, rating: 4.5, reviews: 2009, desc: 'A pre-paired, ready-out-of-the-box door chime with a 500 ft range and 1–2 year battery life — the simplest way to monitor one key door.', features: ['Pre-paired, ready to use', '500 ft range, 58 chimes', '120 dB max volume', '1–2 yr ultra-low-power battery'], pros: ['No setup needed', 'Long battery life', 'Affordable'], cons: ['One sensor in base kit'], bestFor: ['front or basement door', 'simple monitoring', 'long battery life'], specs: { type: 'Door chime', range: '500 ft', volume: '120 dB', sensors: '1' } }),
  mk({ id: 'ge-door-alarm-2pack', name: 'GE Personal Security Door & Window Alarm (2-Pack)', brand: 'GE / UltraPro', sub: 'contact-alarm', q: 'GE personal security window door alarm 2 pack 120dB', badge: 'Best Budget', price: 12.79, rating: 4.5, reviews: 16771, desc: 'The easiest entry point: a trusted 120 dB stick-on alarm with OFF/CHIME/ALARM modes and pre-installed batteries — perfect for a single bedroom or bathroom door.', features: ['120 dB alarm', 'OFF / CHIME / ALARM switch', 'Pre-installed batteries', 'Double-sided tape, no wiring'], pros: ['Very inexpensive', 'Loud and simple', 'No tools to install'], cons: ['No caregiver pager/receiver'], bestFor: ['one or two doors', 'early-stage wandering', 'budget setups'], specs: { type: 'Contact alarm', volume: '120 dB', modes: 'Off/Chime/Alarm', pack: '2' } }),
  mk({ id: 'ultrapro-ge-door-alarm-4pack', name: 'UltraPro (GE) Door & Window Alarm (4-Pack)', brand: 'GE / UltraPro', sub: 'contact-alarm', q: 'UltraPro GE door window alarm 4 pack 120dB chime', badge: 'Best Small Home', price: 20.14, rating: 4.5, reviews: 11508, desc: 'Four of the same trusted GE alarms with a low-battery LED and CHIME or ALARM modes — enough to cover the key doors of a small home.', features: ['120 dB, 3-mode switch', 'Low-battery LED indicator', 'Batteries pre-installed', 'Wireless tape install'], pros: ['Covers several doors', 'Reliable GE design', 'Chime or full alarm'], cons: ['No remote pager'], bestFor: ['small homes', 'doors + windows', 'apartments'], specs: { type: 'Contact alarm', volume: '120 dB', modes: 'Off/Chime/Alarm', pack: '4' } }),
  mk({ id: 'ultrapro-ge-door-alarm-5pack', name: 'UltraPro (GE) Door & Window Alarm (5-Pack)', brand: 'GE / UltraPro', sub: 'contact-alarm', q: 'UltraPro GE door window alarm 5 pack 120dB lifetime warranty', badge: 'Best for Whole Home', price: 21.15, rating: 4.5, reviews: 16771, desc: 'A five-pack of the most-reviewed door/window alarms on Amazon — a battery test button, low-battery LED, and lifetime warranty for whole-home coverage.', features: ['120 dB, 3-mode switch', 'Battery test button + low-battery LED', 'Double-sided tape, no wiring', 'Lifetime warranty'], pros: ['Best per-unit value', 'Cover every exterior door', 'Lifetime warranty'], cons: ['No remote pager'], bestFor: ['whole-home coverage', 'multiple exits', 'value'], specs: { type: 'Contact alarm', volume: '120 dB', modes: 'Off/Chime/Alarm', pack: '5' } }),
  mk({ id: 'amhey-motion-door-chime', name: 'AMHEY Wireless Motion Sensor Door Chime', brand: 'AMHEY', sub: 'motion-sensor', q: 'AMHEY wireless motion sensor door chime PIR caregiver alert', badge: 'Best Motion Sensor', price: 22.66, rating: 4.5, reviews: 926, desc: 'A PIR motion sensor that alerts you as a loved one approaches the door — before they ever touch the handle — across a 500 ft range.', features: ['PIR detects approach (16–26 ft / 110°)', '500 ft range to receiver', '32 chimes, 5 volume levels (0–110 dB)', 'Expandable to 20+ sensors'], pros: ['Warns before the door opens', 'No contact sensor to defeat', 'Adjustable volume + LED'], cons: ['Needs careful placement to avoid false triggers'], bestFor: ['early-warning wandering alerts', 'hallways near exits', 'layered setups'], specs: { type: 'Motion sensor', range: '500 ft', detection: '16–26 ft / 110°', volume: '110 dB' } }),
  mk({ id: 'calltou-caregiver-pager', name: 'CallToU Wireless Caregiver Pager (2 Buttons + 2 Receivers)', brand: 'CallToU', sub: 'pager', q: 'CallToU wireless caregiver pager call button system 2 receiver', badge: 'Best Call Button', price: 33.59, rating: 4.6, reviews: 7142, desc: 'A caregiver call system: waterproof SOS buttons worn as a pendant or mounted by the bed let a loved one summon help from up to 500 ft away.', features: ['2 SOS call buttons + 2 plug-in receivers', '500 ft range, 55 ringtones', '110 dB, 5 volume levels', 'IP55 waterproof buttons'], pros: ['Lets the senior call for help', 'Wearable or wall-mounted', 'Waterproof buttons'], cons: ['Call button, not a door sensor'], bestFor: ['summoning a caregiver', 'bedside/bathroom help', 'two-way peace of mind'], specs: { type: 'Caregiver pager', range: '500 ft', buttons: '2', receivers: '2' } }),
  mk({ id: 'sti-6400-exit-stopper', name: 'STI-6400 Exit Stopper Multifunction Door Alarm', brand: 'STI', sub: 'exit-stopper', q: 'STI-6400 exit stopper multifunction door alarm key override', badge: 'Best for Memory Care', price: 76.28, rating: 4.6, reviews: 509, desc: 'A professional-grade "stop sign" exit alarm with a key-operated override and four alarm durations — the standard for memory-care units and group homes.', features: ['105 dB with visual stop-sign deterrent', '4 durations (10 beeps / 30 s / 3 min / continuous)', 'Key-operated override for authorized exits', 'Indestructible polycarbonate, 3-yr warranty'], pros: ['Visual + audible deterrent', 'Staff key override', 'Built to last'], cons: ['Most expensive option', '9V battery'], bestFor: ['memory care units', 'group homes', 'high wandering risk'], specs: { type: 'Exit stopper', volume: '105 dB', override: 'Key', power: '9V battery' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} door-wander-alarms. Catalog now ${p.length} products.`);
