import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'dementia-clocks', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'american-lifetime-dementia-clock', name: 'American Lifetime Day Clock (Large Display)', brand: 'American Lifetime', sub: 'day-clock', q: 'American Lifetime dementia day clock large display no abbreviations 5 alarms', badge: 'Best Overall', price: 59.95, rating: 4.6, reviews: 23272, desc: 'The most-trusted dementia clock — a 9.5" display that spells out the full day with no abbreviations, shows morning/afternoon/evening/night, and includes 5 alarms and auto-dimming.', features: ['9.5" display, no abbreviations', 'Morning/Afternoon/Evening/Night', '5 custom alarms, auto-dimming', 'Backup power, 8 languages, US support'], pros: ['Clearest day/time-of-day display', 'Most trusted brand', 'Simple caregiver setup'], cons: ['Highest price here'], bestFor: ['core dementia orientation', 'reducing confusion', 'home & care facilities'], specs: { size: '9.5"', display: 'Full words', alarms: '5', dimming: 'Auto' } }),
  mk({ id: 'jall-8in-day-clock', name: 'JALL 8" Digital Calendar Day Clock', brand: 'JALL', sub: 'day-clock', q: 'JALL 8 inch digital calendar day clock dementia hourly chime auto dimming', badge: 'Best Voice Chime', price: 49.99, rating: 4.6, reviews: 16974, desc: 'An 8" wide-angle IPS clock with 12 alarms and an hourly chime that announces the time and date aloud — with five time periods and auto-dimming at 7PM/7AM.', features: ['8" IPS wide-angle display', '12 custom alarms', 'Hourly chime announces time + date', '5 time periods, auto-dimming'], pros: ['Speaks the time aloud hourly', 'Wide viewing angle', 'Lots of alarms'], cons: ['Chime may not suit light sleepers'], bestFor: ['audible time cues', 'medication reminders', 'wall or tabletop'], specs: { size: '8"', alarms: '12', chime: 'Hourly voice', dimming: 'Auto' } }),
  mk({ id: 'raynic-large-dementia-clock', name: 'Raynic 11.5" Large-Display Calendar Clock', brand: 'Raynic', sub: 'large-display', q: 'Raynic 11.5 inch large display digital calendar clock day date temperature', badge: 'Largest Display', price: 33.99, rating: 4.6, reviews: 14284, desc: 'The largest display here at 11.5" — readable from across a room or doorway — showing day, date, and indoor temperature, with 5 brightness levels, 3 alarms, and 2 USB ports.', features: ['11.5" LED display (largest)', 'Day + date + indoor temperature', '5 brightness levels, 3 alarms', '2 USB ports, backup battery'], pros: ['Visible across any room', 'Adjustable brightness', 'USB charging built in'], cons: ['Uses some abbreviations'], bestFor: ['shared / care-facility rooms', 'low vision', 'visibility from bed'], specs: { size: '11.5"', extra: 'Indoor temp', brightness: '5 levels', usb: '2 ports' } }),
  mk({ id: 'ssya-day-clock', name: 'SSYA 7" High-Contrast Memory-Loss Day Clock', brand: 'SSYA', sub: 'day-clock', q: 'SSYA digital calendar alarm clock dementia 7 inch HD non abbreviated high contrast', badge: 'Best High-Contrast', price: 29.99, rating: 4.6, reviews: 7222, desc: 'A 7" HD clock that spells out the full time of day (morning, afternoon, evening, night, predawn) with extra-large white digits on deep black, plus 12 tagged alarms.', features: ['Spells out time of day fully', 'Extra-large white-on-black digits', '12 alarms with tags (Meal/Medicine)', 'Glare-free, auto-dimming'], pros: ['Excellent high-contrast readability', 'Tagged medication alarms', 'Affordable'], cons: ['Smaller than premium models'], bestFor: ['high-contrast clarity', 'low vision + dementia', 'medication tags'], specs: { size: '7"', display: 'White on black', alarms: '12', dimming: 'Auto' } }),
  mk({ id: 'dreamsky-bedside-dementia-clock', name: 'DreamSky 7.6" Bedside Day Clock with USB', brand: 'DreamSky', sub: 'large-display', q: 'DreamSky large digital clock date day of week 7.6 inch USB battery backup auto dimming', badge: 'Best Bedside', price: 26.99, rating: 4.6, reviews: 1428, desc: 'A 7.6" bedside clock showing time, date, day of week, and indoor temperature, with a 4-level alarm volume for the hard of hearing, auto-dimming, USB charging, and battery backup.', features: ['7.6" display, day of week + temp', 'Auto-dimmer (9PM / 7AM)', '4-level alarm volume', 'USB port, battery backup'], pros: ['Loud alarm option', 'Good bedside size', 'USB charging + backup'], cons: ['Fewer dementia-specific phases'], bestFor: ['bedside use', 'hard of hearing', 'simple orientation'], specs: { size: '7.6"', volume: '4 levels', dimming: 'Auto', backup: 'Battery' } }),
  mk({ id: 'roxicosly-dementia-clock', name: 'Roxicosly 7" Day Clock with Photo Frame', brand: 'Roxicosly', sub: 'reminder-clock', q: 'Roxicosly clock day date elderly 7 inch 20 alarms reminders photo frame', badge: 'Best Photo-Frame Combo', price: 29.99, rating: 4.6, reviews: 1820, desc: 'A 7" HD clock with 20 alarms and 20 reminders, six time phases with sun/moon icons, and a built-in digital photo frame — familiar family faces ease anxiety.', features: ['20 alarms + 20 reminders', '6 time phases with sun/moon icons', 'Digital photo frame (USB/SD)', '12 themes, memory backup'], pros: ['Photos comfort and reassure', 'Lots of reminders', 'Highly customizable'], cons: ['Busier interface to set up'], bestFor: ['easing anxiety with photos', 'many reminders', 'home use'], specs: { size: '7"', alarms: '20', reminders: '20', extra: 'Photo frame' } }),
  mk({ id: 'soobest-dementia-clock', name: 'Soobest 7" Day Clock with 20 Visual Reminders', brand: 'Soobest', sub: 'reminder-clock', q: 'Soobest dementia digital clock seniors 20 alarm reminders icons time periods 7 inch', badge: 'Best Reminders', price: 27.99, rating: 4.6, reviews: 1425, desc: 'A 7" HD clock with 20 programmable reminders that show specific icons (shower, meals, medicine), six time-period indicators, three ringtones, and four display modes.', features: ['20 reminders with icons', '6 time-period indicators', '3 ringtones, volume 1–10', '4 display modes, USB-C'], pros: ['Icon reminders are easy to grasp', 'Flexible display modes', 'Adjustable volume'], cons: ['Newer brand'], bestFor: ['medication & task reminders', 'icon-based cues', 'caregiver scheduling'], specs: { size: '7"', reminders: '20', modes: '4', power: 'USB-C' } }),
  mk({ id: 'mitoart-talking-dementia-clock', name: 'Mitoart 7" Talking Dementia Clock', brand: 'Mitoart', sub: 'talking-clock', q: 'Mitoart digital alarm clock dementia voice announcement talking 9 languages remote', badge: 'Best Talking Clock', price: 25.99, rating: 4.7, reviews: 754, desc: 'Press OK (or the remote) and the clock announces the time aloud in nine languages — a bold, no-abbreviation display with medication and schedule alarms for users with vision loss.', features: ['Announces time aloud (9 languages)', 'Bold no-abbreviation display', 'Medication + schedule alarms', 'Auto-dimming, one-click setup'], pros: ['No reading required', 'Highest rating, lowest price', 'Simple to set up'], cons: ['Smaller display'], bestFor: ['vision impairment + dementia', 'hearing the time', 'budget buyers'], specs: { size: '7"', voice: '9 languages', alarms: 'Multiple', dimming: 'Auto' } }),
  mk({ id: 'flyruit-dementia-clock', name: 'FLYRUIT 7" Dementia Clock with Visual Reminders', brand: 'FLYRUIT', sub: 'reminder-clock', q: 'FLYRUIT 7 inch dementia clock seniors visual reminders icons HD IPS remote auto dimming', badge: 'Best Visual Reminders', price: 29.99, rating: 4.7, reviews: 1042, desc: 'A 7" HD IPS clock with five time phases and 10 customizable visual reminders with icons (medication, hydration, walks), plus 6 alarms with gentle tones and a remote.', features: ['7" IPS 1024×600 HD', '5 time phases, 10 visual reminders', '6 alarms with 5 gentle tones', 'Remote, 4 color themes, auto-dimming'], pros: ['Clear icon reminders', 'Gentle, non-startling tones', 'Top rating, remote included'], cons: ['Fewer reviews than flagships'], bestFor: ['gentle reminders', 'hydration / medication cues', 'home care'], specs: { size: '7"', reminders: '10 visual', alarms: '6', remote: 'Yes' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} dementia-clocks. Catalog now ${p.length} products.`);
