import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'adaptive-eating-aids', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'vincere-weighted-utensils', name: 'Vincere Weighted Utensils for Tremors (4-Piece Set)', brand: 'Vincere', sub: 'weighted-utensils', q: 'Vincere weighted utensils tremors Parkinsons 4 piece set travel bag', badge: 'Best Overall', price: 54.99, rating: 4.7, reviews: 1142, desc: 'A premium 4-piece weighted set (7 oz each) whose stabilizing mass counteracts hand tremors, with ergonomic non-slip handles and a roll-up travel bag.', features: ['4-piece set, 7 oz per utensil', 'Heavy weight steadies tremors', 'Ergonomic wide non-slip handles', 'Dishwasher safe + travel bag'], pros: ['Effectively reduces tremor spill', 'Discreet, premium look for dining out', 'Comes with a travel roll'], cons: ['Priciest set here'], bestFor: ['Parkinson’s and tremors', 'dining out', 'steadier eating'], specs: { type: 'Weighted', pieces: '4', weight: '7 oz each', care: 'Dishwasher safe' } }),
  mk({ id: 'bunmo-adaptive-utensils', name: 'BUNMO Adaptive Utensils (4-Piece Set)', brand: 'BUNMO', sub: 'adaptive-utensils', q: 'BUNMO adaptive utensils elderly weighted hand tremors 4 piece foam', badge: 'Best for Arthritis', price: 23.99, rating: 4.6, reviews: 7220, desc: 'The most-reviewed adaptive set: lightweight foam handles that reduce grip strain, plus a curved rocker knife that cuts without a sawing motion.', features: ['4 pieces with curved rocker knife', 'Lightweight foam handles', 'Reduce grip strain', 'Dishwasher safe + travel wrap'], pros: ['Easy on weak, arthritic hands', 'Rocker knife needs no sawing', 'Most-reviewed, great value'], cons: ['Lighter — less tremor damping than weighted'], bestFor: ['arthritis and weak grip', 'one-handed cutting', 'everyday use'], specs: { type: 'Built-up foam', pieces: '4', knife: 'Rocker', care: 'Dishwasher safe' } }),
  mk({ id: 'weighted-silverware-cuffs', name: 'Weighted Silverware Set with 2 Universal Cuffs (4-Piece)', brand: 'Adaptive', sub: 'weighted-utensils', q: 'weighted silverware hand tremors Parkinsons 4 piece universal cuffs', badge: 'Best with Grip Cuffs', price: 32.39, rating: 4.6, reviews: 126, desc: 'A heavy-duty weighted 4-piece set that includes two universal cuffs to strap a utensil to the hand — built for Parkinson’s, stroke recovery, and neuropathy.', features: ['4-piece weighted set', '2 universal hand cuffs included', 'Premium stainless steel', 'Dishwasher safe'], pros: ['Cuffs help a very weak grip', 'Heavy enough to steady tremors', 'Good for stroke recovery'], cons: ['Fewer reviews than top sellers'], bestFor: ['very weak grip', 'stroke and neuropathy', 'tremor + grip issues'], specs: { type: 'Weighted', pieces: '4', extras: '2 cuffs', material: 'Stainless' } }),
  mk({ id: 'nourislif-adaptive-utensils', name: 'Nourislif Adaptive Utensils (4-Piece, Foam Grip)', brand: 'Nourislif', sub: 'adaptive-utensils', q: 'Nourislif adaptive utensils foam grip handles rocker knife 4 piece', badge: 'Best Budget', price: 9.99, rating: 4.5, reviews: 1461, desc: 'A budget 4-piece set with 1.25" built-up foam grips and a rocker knife — rustproof stainless steel, backed by a 1-year guarantee.', features: ['Tablespoon, teaspoon, fork + rocker knife', '1.25" wide foam grip handles', 'Rustproof stainless steel', '1-year guarantee'], pros: ['Lowest price here', 'Comfortable built-up grips', 'Includes a rocker knife'], cons: ['Not weighted for tremors'], bestFor: ['budget buyers', 'mild arthritis', 'trying adaptive utensils'], specs: { type: 'Built-up foam', pieces: '4', grip: '1.25"', knife: 'Rocker' } }),
  mk({ id: 'providence-scoop-plate', name: 'Providence Spillproof 9" Adaptive Scoop Plate (3-Pack)', brand: 'Providence Spillproof', sub: 'scoop-plate', q: 'Providence Spillproof scoop plate adaptive bowl raised edges 3 pack', badge: 'Best Scoop Plate', price: 28.09, rating: 4.6, reviews: 1434, desc: 'A scoop plate with built-in raised edges that let food be scooped in one motion, on a non-slip base — microwave and dishwasher safe.', features: ['Raised edges for one-motion scooping', 'Non-slip base', 'Microwave + dishwasher safe', 'BPA-free, 25+ yr brand'], pros: ['Great for one-handed eating', 'Keeps food from sliding off', 'Trusted brand'], cons: ['Plain white only'], bestFor: ['one-handed / stroke recovery', 'tremors', 'independent eating'], specs: { type: 'Scoop plate', size: '9"', pack: '3', base: 'Non-slip' } }),
  mk({ id: 'special-supplies-scoop-plates', name: 'Special Supplies Adaptive Scoop Plates (3-Pack, High-Contrast)', brand: 'Special Supplies', sub: 'scoop-plate', q: 'Special Supplies adaptive scoop plates high contrast white blue red 3 pack', badge: 'Best High-Contrast', price: 24.99, rating: 4.7, reviews: 64, desc: 'High-sloped scoop plates in high-contrast white, blue, and red — the bold colors aid food recognition for low vision and dementia — with non-slip rings.', features: ['High sloped rim for scooping', 'High-contrast colors (white/blue/red)', 'Non-slip ring', 'Microwave + dishwasher safe'], pros: ['Contrast aids low vision / dementia', 'High wall keeps food in', 'Set of three colors'], cons: ['Newer listing, fewer reviews'], bestFor: ['low vision and dementia', 'food recognition', 'one-handed eating'], specs: { type: 'Scoop plate', pack: '3', feature: 'High-contrast', base: 'Non-slip ring' } }),
  mk({ id: 'luter-jar-opener', name: 'LUTER Rubber Jar Opener Gripper Pads (4-Pack)', brand: 'LUTER', sub: 'jar-opener', q: 'LUTER rubber jar opener gripper pads arthritis 4 pack', badge: 'Best Jar Opener', price: 5.99, rating: 4.6, reviews: 3339, desc: 'Textured rubber gripper pads in two shapes that add the grip needed to twist open stubborn lids — and double as heat-insulating coasters.', features: ['Textured rubber grip', '2 shapes (round + square)', 'Fits most jar sizes', 'Doubles as a hot-pad/coaster'], pros: ['Extremely affordable', 'Real help for weak grip', 'Multi-purpose'], cons: ['Very tight lids may still need leverage'], bestFor: ['arthritis', 'weak hand grip', 'everyday kitchen use'], specs: { type: 'Jar gripper', pack: '4', shapes: '2', material: 'Rubber' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} adaptive-eating-aids. Catalog now ${p.length} products.`);
