import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'bidet-attachments', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'luxe-neo-120-bidet', name: 'LUXE Bidet NEO 120 Non-Electric Bidet Attachment', brand: 'LUXE Bidet', sub: 'non-electric', q: 'LUXE Bidet NEO 120 non electric single nozzle self cleaning attachment', badge: 'Best Overall', price: 39.99, rating: 4.6, reviews: 101807, desc: "Amazon's best-selling bidet — a single rear-wash nozzle with a self-cleaning guard gate and braided-steel hoses, installed in about 15 minutes with no plumber.", features: ['Single rear-wash nozzle', 'Self-cleaning nozzle guard gate', 'Retractable nozzle, braided steel hoses', '18-month warranty'], pros: ['Most-reviewed bidet on Amazon', 'Simple, reliable, affordable', 'Easy no-plumber install'], cons: ['Cold water only, single nozzle'], bestFor: ['first-time bidet buyers', 'renters', 'everyday hygiene'], specs: { type: 'Non-electric', nozzles: '1 (rear)', water: 'Cold', install: '~15 min' } }),
  mk({ id: 'luxe-neo-185-bidet', name: 'LUXE Bidet NEO 185 Dual-Nozzle Bidet Attachment', brand: 'LUXE Bidet', sub: 'non-electric', q: 'LUXE Bidet NEO 185 dual nozzle non electric self cleaning attachment', badge: 'Best Dual-Nozzle', price: 49.99, rating: 4.6, reviews: 54510, desc: 'Dual nozzles add a frontal feminine wash alongside the rear wash, with a self-cleaning guard gate, adjustable pressure, and stainless-steel hinges.', features: ['Dual nozzles (rear + feminine)', 'Self-cleaning guard gate', 'Adjustable water pressure', 'Braided steel hoses, steel hinges'], pros: ['Adds feminine wash', 'Great for postpartum/UTI prevention', 'Durable build'], cons: ['Cold water only'], bestFor: ['feminine hygiene', 'post-surgery / postpartum', 'couples'], specs: { type: 'Non-electric', nozzles: '2', water: 'Cold', warranty: '18 mo' } }),
  mk({ id: 'pikets-bidet', name: 'PIKETS Dual-Nozzle Bidet Attachment', brand: 'PIKETS', sub: 'non-electric', q: 'PIKETS bidet attachment toilet dual nozzle non electric self cleaning', badge: 'Best Budget', price: 25.99, rating: 4.5, reviews: 8374, desc: 'A budget dual-nozzle attachment with button-mode switching, a self-cleaning nozzle, adjustable pressure, and the longest warranty here at 20 months.', features: ['Dual nozzles (frontal + rear)', 'Button-mode switching', 'Self-cleaning nozzle', '20-month warranty'], pros: ['Lowest price with dual nozzles', 'Longest warranty here', 'Adjustable pressure'], cons: ['Cold water only'], bestFor: ['budget buyers', 'dual-nozzle on a budget', 'renters'], specs: { type: 'Non-electric', nozzles: '2', water: 'Cold', warranty: '20 mo' } }),
  mk({ id: 'luxe-neo-185-plus-bidet', name: 'LUXE Bidet NEO 185 Plus (Slide-In Install)', brand: 'LUXE Bidet', sub: 'non-electric', q: 'LUXE Bidet NEO 185 Plus dual nozzle slide in install 360 self clean chrome', badge: 'Easiest Install', price: 55.99, rating: 4.6, reviews: 7902, desc: 'An upgraded dual-nozzle attachment with a patented slide-in install (no removing the seat), a 360° self-clean mode, EZ-Lift hinges, and a premium chrome finish.', features: ['Patented slide-in install', '360° self-clean mode', 'EZ-Lift hinges for deep cleaning', 'Dual nozzles, chrome finish'], pros: ['Easiest install (no seat removal)', 'Easy to lift and deep-clean', 'Premium look'], cons: ['Cold water only'], bestFor: ['easiest setup', 'easy cleaning', 'dual-nozzle wash'], specs: { type: 'Non-electric', nozzles: '2', install: 'Slide-in', finish: 'Chrome' } }),
  mk({ id: 'luxe-neo-320-warm-bidet', name: 'LUXE Bidet NEO 320 Warm-Water Bidet Attachment', brand: 'LUXE Bidet', sub: 'warm-water', q: 'LUXE Bidet NEO 320 warm water dual nozzle non electric attachment', badge: 'Best Warm Water', price: 59.99, rating: 4.5, reviews: 24609, desc: 'The warm-water pick: connects to the sink hot line for warm wash with no electricity, with dual nozzles, a self-cleaning retractable nozzle, and adjustable temperature.', features: ['Warm water via sink connection', 'No electricity needed', 'Dual nozzles (rear + feminine)', 'Adjustable pressure + temperature'], pros: ['Warm water without wiring', 'Comfort for cold sensitivity', 'Dual-nozzle wash'], cons: ['Needs a nearby hot-water line'], bestFor: ['cold-water sensitivity', 'comfort', 'no-electricity warm wash'], specs: { type: 'Non-electric', water: 'Warm (sink)', nozzles: '2', warranty: '18 mo' } }),
  mk({ id: 'tushy-fresh-bidet', name: 'TUSHY Fresh Ultra-Slim Bidet Attachment', brand: 'TUSHY', sub: 'non-electric', q: 'TUSHY Fresh ultra slim bidet attachment non electric bamboo knob', badge: 'Best Ultra-Slim', price: 49.00, rating: 4.5, reviews: 1962, desc: 'An ultra-slim attachment (52% thinner than standard) with a patented self-rinsing Smart Nozzle, a bamboo control knob, and a 10-minute install on 98% of toilets.', features: ['Ultra-slim (52% thinner)', 'Self-rinsing Smart Nozzle', 'Fits 98% of toilets, <10-min install', 'Adjustable pressure, bamboo knob'], pros: ['Fits tight toilet gaps', 'Self-cleaning nozzle', 'Stylish, quick install'], cons: ['Cold water only'], bestFor: ['modern/tight toilets', 'minimalist look', 'quick install'], specs: { type: 'Non-electric', profile: 'Ultra-slim', nozzle: 'Self-rinsing', install: '<10 min' } }),
  mk({ id: 'tushy-classic-bidet', name: 'TUSHY Classic 3.0 Bidet Attachment', brand: 'TUSHY', sub: 'non-electric', q: 'TUSHY Classic 3.0 bidet toilet seat attachment SmartSpray brushed nickel', badge: 'Best Premium', price: 129.00, rating: 4.5, reviews: 9526, desc: "TUSHY's most refined attachment, with a precision nozzle adjuster for front-and-rear targeting, patented self-cleaning SmartSpray, and a brushed-nickel finish.", features: ['Precision nozzle adjuster (front + rear)', 'Patented self-cleaning SmartSpray', 'Buildup-resistant design', 'Brushed nickel finish'], pros: ['Precise spray targeting', 'Refined, durable design', 'Self-cleaning'], cons: ['Priciest non-electric attachment'], bestFor: ['precise control', 'design-conscious buyers', 'long-term use'], specs: { type: 'Non-electric', nozzles: 'Adjustable', finish: 'Brushed nickel', water: 'Cold' } }),
  mk({ id: 'biobidet-bb2000-seat', name: 'Bio Bidet BB2000 Bliss Electric Bidet Toilet Seat', brand: 'Bio Bidet', sub: 'electric-seat', q: 'Bio Bidet BB2000 Bliss electric bidet toilet seat warm water heated dryer remote', badge: 'Best Electric Seat', price: 459.00, rating: 4.5, reviews: 4252, desc: 'A full electric bidet seat — heated seat, unlimited warm water, warm-air dryer, night light, deodorizer, and a remote — that can eliminate toilet paper entirely.', features: ['Heated seat + unlimited warm water', 'Warm-air dryer, deodorizer, night light', 'Pulsating, oscillating + feminine wash', 'Remote control, 3-yr warranty'], pros: ['Total hands-free hygiene', 'Warm water + dryer (no TP)', 'Named a top bidet by Forbes 2025'], cons: ['Needs a nearby outlet', 'Highest price'], bestFor: ['full independence', 'arthritis / limited mobility', 'no-toilet-paper hygiene'], specs: { type: 'Electric seat', water: 'Warm (unlimited)', dryer: 'Warm air', control: 'Remote' } }),
  mk({ id: 'arofa-handheld-bidet', name: 'Arofa Handheld Toilet Bidet Sprayer', brand: 'Arofa', sub: 'handheld-sprayer', q: 'Arofa handheld toilet bidet sprayer adjustable pressure stainless wall tank mount', badge: 'Best for Independence', price: 25.48, rating: 4.5, reviews: 26576, desc: 'A one-hand ergonomic sprayer with adjustable pressure from gentle to jet — letting a seated user aim directly, ideal for limited mobility, arthritis, and recovery.', features: ['One-hand ergonomic design', 'Adjustable pressure (gentle to jet)', '304 stainless + brass valve, 47" hose', 'Wall or tank mount'], pros: ['Full directional control while seated', 'Great for limited grip/mobility', 'Reduces or eliminates wiping'], cons: ['Mounting needs a few minutes'], bestFor: ['arthritis / weak grip', 'post-surgery & postpartum', 'maximum independence'], specs: { type: 'Handheld sprayer', control: 'One-hand', hose: '47"', mount: 'Wall/tank' } }),
  mk({ id: 'purrfectzone-handheld-bidet', name: 'PurrfectZone Handheld Bidet Sprayer Kit', brand: 'PurrfectZone', sub: 'handheld-sprayer', q: 'PurrfectZone bidet sprayer handheld kit stainless steel braided hose', badge: 'Best Handheld Kit', price: 28.99, rating: 4.6, reviews: 20203, desc: 'An American-brand handheld kit with adjustable flow from soft to jet, a leakproof braided stainless hose, precision fittings, and everything needed to install.', features: ['Adjustable flow (soft to jet)', 'Leakproof braided stainless hose', 'Precision-engineered fittings', 'Compact, all fittings included'], pros: ['Complete kit, easy install', 'Reliable leakproof fittings', 'Compact for small bathrooms'], cons: ['Mounted sprayer, not an attachment'], bestFor: ['small bathrooms', 'directional control', 'DIY install'], specs: { type: 'Handheld sprayer', flow: 'Adjustable', hose: 'Braided stainless', brand: 'USA' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} bidet-attachments. Catalog now ${p.length} products.`);
