import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'wheelchair-ramps', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'vevor-3in-threshold-ramp', name: 'VEVOR 3" Rise Rubber Threshold Ramp', brand: 'VEVOR', sub: 'rubber-threshold', q: 'VEVOR 3 inch rise rubber threshold wheelchair ramp doorway non slip', badge: 'Best Overall', price: 47.90, rating: 4.6, reviews: 1978, desc: 'A one-piece recycled-rubber ramp for a 3-inch rise, 35.6" wide with beveled edges all around and a grooved non-slip surface — fits wheelchairs up to 26.8".', features: ['3" rise, 35.6" wide', '2200 lb capacity', 'Beveled edges all sides', 'Grooved non-slip, no tools'], pros: ['Sturdy one-piece design', 'No installation needed', 'High capacity'], cons: ['Heavy to reposition'], bestFor: ['3" door thresholds', 'power wheelchairs & scooters', 'porches'], specs: { rise: '3"', width: '35.6"', capacity: '2200 lb', type: 'Rubber' } }),
  mk({ id: 'vevor-1-6in-threshold-ramp', name: 'VEVOR 1.6" Rise Cuttable Rubber Threshold Ramp', brand: 'VEVOR', sub: 'rubber-threshold', q: 'VEVOR 1.6 inch rise cuttable natural rubber threshold ramp doorway', badge: 'Best Value', price: 26.90, rating: 4.6, reviews: 938, desc: 'A natural-rubber ramp for a 1.6-inch rise that cuts to fit any doorway, with anti-slip stripes and double-sided tape included — at a great price.', features: ['1.6" rise, 35.4" wide', 'Cuttable to fit any doorway', 'Anti-slip stripes', 'Double-sided tape included'], pros: ['Lowest price', 'Trim to exact width', 'Eco-friendly rubber'], cons: ['Lower rise only'], bestFor: ['low door thresholds', 'walkers & wheelchairs', 'budget buyers'], specs: { rise: '1.6"', width: '35.4"', cuttable: 'Yes', type: 'Rubber' } }),
  mk({ id: 'nuvium-1in-threshold-ramp', name: 'Nuvium 1" Rise Natural Rubber Threshold Ramp', brand: 'Nuvium', sub: 'rubber-threshold', q: 'Nuvium 1 inch rise natural rubber threshold ramp doorway cuttable', badge: 'Best for Low Rises', price: 33.90, rating: 4.5, reviews: 614, desc: 'A 1-inch natural-rubber ramp, 35.5" wide and rated to 2000 lb, that is free-cut and spliceable to fit any doorway, with adhesive backing and non-slip grooves.', features: ['1" rise, 35.5" wide', '2000 lb capacity', 'Cut & splice to any width', 'Double-sided adhesive, non-slip grooves'], pros: ['Smooths small thresholds', 'Trims to fit perfectly', 'Strong adhesive backing'], cons: ['Only a 1" rise'], bestFor: ['low door tracks', 'no trip hazard', 'walkers & scooters'], specs: { rise: '1"', width: '35.5"', capacity: '2000 lb', cuttable: 'Yes' } }),
  mk({ id: 'vevor-4in-cord-threshold-ramp', name: 'VEVOR 4" Rise Rubber Threshold Ramp with Cord Channels', brand: 'VEVOR', sub: 'rubber-threshold', q: 'VEVOR 4 inch rise rubber threshold ramp cord cover channels wheelchair', badge: 'Best with Cord Channels', price: 86.90, rating: 4.6, reviews: 889, desc: 'A 4-inch rubber ramp with three built-in cable channels to route cords safely across a doorway — raised-button non-slip surface, pet-friendly, one-piece.', features: ['4" rise, 41.8"×24"', '2200 lb capacity', '3 built-in cord channels', 'Raised-button non-slip surface'], pros: ['Hides cables at the threshold', 'High weight capacity', 'Pet-friendly grip'], cons: ['Heaviest threshold ramp here'], bestFor: ['4" rises with cords', 'home offices', 'powered doorways'], specs: { rise: '4"', size: '41.8×24"', capacity: '2200 lb', extra: '3 cord channels' } }),
  mk({ id: 'ezaccess-25in-rubber-ramp', name: 'EZ-ACCESS Transitions 2.5" Angled Rubber Threshold Ramp', brand: 'EZ-ACCESS', sub: 'rubber-threshold', q: 'EZ-ACCESS Transitions angled entry rubber threshold ramp 2.5 inch made USA', badge: 'Best Premium (USA)', price: 183.33, rating: 4.6, reviews: 83, desc: 'A made-in-USA rubber threshold ramp for a 2.5-inch rise, 43" wide with dirt-trapping grooves and edgeless drainage — trimmable to fit, with a lifetime warranty.', features: ['2.5" rise, 43" wide', '850 lb capacity', 'Recessed dirt-trapping grooves', 'Trimmable, lifetime warranty (USA)'], pros: ['Premium build + lifetime warranty', 'Water drainage design', 'Wide for commercial doors'], cons: ['Priciest threshold ramp'], bestFor: ['wide entries', 'OT-recommended installs', 'long-term use'], specs: { rise: '2.5"', width: '43"', capacity: '850 lb', origin: 'USA' } }),
  mk({ id: 'fachnuo-2ft-folding-ramp', name: 'FACHNUO 2 ft Portable Folding Aluminum Wheelchair Ramp', brand: 'FACHNUO', sub: 'folding-ramp', q: 'FACHNUO 2FT portable folding aluminum wheelchair ramp lightweight', badge: 'Lightest Portable', price: 84.98, rating: 4.5, reviews: 1450, desc: 'A compact 2-foot aluminum ramp for 2–6" step heights — just 10.9 lb with a built-in carry handle, reflective strips, and a fold to 3.2" thick.', features: ['24"×29.2", 800 lb capacity', 'Fits 2–6" step heights', 'Only 10.9 lb, carry handle', 'Folds to 3.2", reflective strips'], pros: ['Very light and portable', 'Great for curbs & cars', 'Strong stainless hinge'], cons: ['Short — low rises only'], bestFor: ['single steps & curbs', 'travel & vehicles', 'thresholds'], specs: { length: '2 ft', rise: '2–6"', weight: '10.9 lb', capacity: '800 lb' } }),
  mk({ id: 'vnn-4ft-folding-ramp', name: 'VNN 4 ft Portable Folding Aluminum Wheelchair Ramp', brand: 'VNN', sub: 'folding-ramp', q: 'VNN 4FT portable folding non slip aluminum wheelchair ramp home steps', badge: 'Best for Steps', price: 139.99, rating: 4.5, reviews: 1876, desc: 'A 4-foot folding aluminum ramp for 4–12" step heights, with a double non-slip layer, side baffles, transition plates, and reflective markers for safety.', features: ['48"×29.2", 800 lb capacity', 'Fits 4–12" step heights', 'Double non-slip layer + baffles', 'Transition plates, reflective'], pros: ['Handles a flight of 1–2 steps', 'Secure non-slip surface', 'Edge baffles prevent roll-off'], cons: ['Heavier at 23.8 lb'], bestFor: ['home steps & porches', 'vans', 'higher rises'], specs: { length: '4 ft', rise: '4–12"', weight: '23.8 lb', capacity: '800 lb' } }),
  mk({ id: 'fachnuo-8ft-folding-ramp', name: 'FACHNUO 8 ft Portable Folding Aluminum Wheelchair Ramp', brand: 'FACHNUO', sub: 'folding-ramp', q: 'FACHNUO 8FT portable folding aluminum wheelchair ramp large steps suitcase', badge: 'Best for Tall Steps', price: 349.98, rating: 4.5, reviews: 1450, desc: 'An 8-foot folding ramp for tall 8–24" rises, with a suitcase-style handle, matte pleated non-slip surface, side baffles, and extended guide rails.', features: ['96"×29", 800 lb capacity', 'Fits 8–24" step heights', 'Suitcase-style carry handle', 'Pleated non-slip + guide rails'], pros: ['Spans tall porches & stoops', 'Gentle slope for safety', 'Extended guide rails'], cons: ['Bulky and heavy (57 lb)'], bestFor: ['tall porches & stoops', 'multiple steps', 'vans'], specs: { length: '8 ft', rise: '8–24"', weight: '57 lb', capacity: '800 lb' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} wheelchair-ramps. Catalog now ${p.length} products.`);
