import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'low-vision-magnifiers', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'magnipros-6x-rechargeable-magnifier', name: 'MagniPros 6X Rechargeable Page Magnifier', brand: 'MagniPros', sub: 'page', q: 'MagniPros 6X rechargeable handheld page magnifier LED', badge: 'Best Overall', price: 23.95, rating: 4.6, reviews: 6081, desc: 'A patented rectangular lens that mimics natural left-to-right reading, with anti-glare LEDs and 8–12 hr battery.', features: ['Patented 6X rectangular reading lens', '3 color light modes', 'Anti-glare SMD LEDs', '8–12 hr rechargeable battery'], pros: ['Natural reading shape', 'Bright, glare-free light', 'No battery cost'], cons: ['Larger than pocket models'], bestFor: ['extended reading', 'mail and books', 'low vision'], specs: { magnification: '6X', lens: 'Rectangular', power: 'USB rechargeable', light: 'Anti-glare LED' } }),
  mk({ id: 'nazano-handheld-magnifier', name: 'Nazano 3X Illuminated Handheld Magnifier', brand: 'Nazano', sub: 'handheld', q: 'Nazano 3X illuminated handheld magnifying glass LED', badge: 'Best Budget', price: 9.69, rating: 4.5, reviews: 20986, desc: 'A budget handheld with a 3.15-inch double glass lens and 12 bright LEDs — great for prescriptions and labels.', features: ['3.15" double glass lens', '12 ultra-bright LEDs', 'Scratch-resistant lens', 'Ergonomic grip (2 AA)'], pros: ['Very affordable', 'Bright and clear', 'Easy to hold'], cons: ['Uses AA batteries'], bestFor: ['reading print', 'prescriptions', 'macular degeneration'], specs: { magnification: '3X', lens: '3.15" glass', power: '2 AA', leds: '12' } }),
  mk({ id: 'jmh-handheld-magnifier', name: 'JMH 3X Handheld LED Magnifier', brand: 'JMH', sub: 'handheld', q: 'JMH 3X handheld LED magnifier 3 color modes', badge: 'Best Handheld', price: 9.99, rating: 4.5, reviews: 15463, desc: 'An 80mm glass lens with 18 LEDs in three color modes and stepless dimming — versatile and affordable.', features: ['80mm glass lens', '18 LEDs, 3 color modes', 'Stepless dimmable', 'Includes carrying bag'], pros: ['Adjustable light color/brightness', 'Clear glass lens', 'Comes with a bag'], cons: ['Uses batteries'], bestFor: ['pill bottles', 'newspapers', 'everyday reading'], specs: { magnification: '3X', lens: '80mm glass', leds: '18', modes: '3 color' } }),
  mk({ id: 'aixpi-large-magnifier', name: 'AIXPI 3X Large 5" Illuminated Magnifier', brand: 'AIXPI', sub: 'handheld', q: 'AIXPI 3X large 5 inch illuminated magnifier UV light', badge: 'Best Large Lens', price: 17.99, rating: 4.5, reviews: 1203, desc: 'An extra-large 5-inch distortion-free lens with 24 LEDs plus a UV light, yet ultralight at 200g.', features: ['Extra-large 5" lens', '24 LEDs + 1 UV light', 'Distortion-free', 'Ultralight 200g (3 AAA)'], pros: ['Big viewing area', 'Very light to hold', 'UV light for currency/stamps'], cons: ['Uses AAA batteries'], bestFor: ['wide viewing', 'reading large areas', 'hobbies'], specs: { magnification: '3X', lens: '5"', leds: '24 + UV', weight: '200 g' } }),
  mk({ id: 'gaborish-rechargeable-magnifier', name: 'GABORISH 10X/20X/45X Rechargeable Magnifier', brand: 'GABORISH', sub: 'page', q: 'GABORISH 10X 20X 45X rechargeable illuminated magnifier', badge: 'Highest Magnification', price: 24.99, rating: 4.6, reviews: 836, desc: 'Three magnification levels (10X/20X/45X) in one, with a 5.2-inch shatterproof lens and 37 LEDs.', features: ['10X / 20X / 45X in one', '5.2" shatterproof optical lens', '37 LEDs, 3 light modes', 'USB rechargeable'], pros: ['Very high magnification', 'Shatterproof lens', 'Rechargeable'], cons: ['High magnification needs a steady hand'], bestFor: ['severe low vision', 'fine detail', 'macular degeneration'], specs: { magnification: '10X/20X/45X', lens: '5.2" shatterproof', leds: '37', power: 'USB rechargeable' } }),
  mk({ id: 'akkycvs-folding-magnifier', name: 'AKKYCVS 5X Folding Rechargeable Page Magnifier', brand: 'AKKYCVS', sub: 'page', q: 'AKKYCVS 5X folding rechargeable LED page magnifier', badge: 'Best Portable', price: 18.89, rating: 4.6, reviews: 1494, desc: 'A folding handle for easy storage, a 4.72x3" rectangular lens, and 12 dimmable LEDs with USB-C charging.', features: ['Foldable handle for storage', '4.72"×3" rectangular lens', '12 dimmable LEDs', 'USB-C rechargeable'], pros: ['Folds away compactly', 'Adjustable brightness', 'Lightweight'], cons: ['Acrylic lens (not glass)'], bestFor: ['travel', 'reading on the go', 'low vision'], specs: { magnification: '5X', lens: '4.72×3"', leds: '12 dimmable', power: 'USB-C' } }),
  mk({ id: 'krstlv-desk-lamp-magnifier', name: 'Krstlv 10X LED Desk Magnifying Lamp', brand: 'Krstlv', sub: 'desk-lamp', q: 'Krstlv 10X LED desk magnifying lamp gooseneck stand', badge: 'Best Hands-Free Desk', price: 29.99, rating: 4.6, reviews: 1617, desc: 'A hands-free 4.3-inch HD glass lens on a flexible gooseneck, with 5 color modes and a metal tool-tray base.', features: ['4.3" HD glass lens', '360° flexible 12.6" gooseneck', '5 color modes + dimming', 'Metal base / tool tray'], pros: ['Hands-free for crafts', 'Bright, adjustable light', 'Stable base'], cons: ['AC-powered (corded)'], bestFor: ['needlework', 'hobbies', 'repairs'], specs: { magnification: '10X', lens: '4.3" glass', arm: '360° gooseneck', power: 'AC' } }),
  mk({ id: 'guoubuo-headset-magnifier', name: 'GUOUBUO Rechargeable Headset Magnifier', brand: 'GUOUBUO', sub: 'wearable', q: 'GUOUBUO rechargeable magnifying headset glasses LED', badge: 'Best Wearable', price: 19.99, rating: 4.5, reviews: 1558, desc: 'A head-mounted magnifier with four detachable lenses and a directional LED — both hands free for close work.', features: ['4 detachable lenses (1.5X–5X)', 'Adjustable directional LED', '3.5–7 hr battery, USB-C', 'Fits over prescription glasses'], pros: ['Hands completely free', 'Multiple magnification levels', 'Works over glasses'], cons: ['Headset can feel bulky'], bestFor: ['jewelry/sewing', 'crafts', 'detailed close work'], specs: { magnification: '1.5X–5X', type: 'Head-mounted', power: 'USB-C', light: 'Directional LED' } }),
  mk({ id: 'eyoyo-video-magnifier', name: 'Eyoyo 3.5" Electronic Video Magnifier', brand: 'Eyoyo', sub: 'electronic', q: 'Eyoyo 3.5 inch digital electronic video magnifier low vision', badge: 'Best Electronic', price: 79.99, rating: 4.6, reviews: 417, desc: 'A digital video magnifier with 2X–25X zoom and 8 high-contrast color modes — the gold standard for severe low vision.', features: ['2X–25X zoom', '8 color modes (white-on-black, etc.)', 'Screen freeze + snapshot', 'AV output to TV, 3+ hr battery'], pros: ['High-contrast modes aid macular degeneration', 'Very high zoom', 'Freeze and view on a TV'], cons: ['Pricier than optical magnifiers'], bestFor: ['severe low vision', 'macular degeneration', 'high contrast needs'], specs: { magnification: '2X–25X', screen: '3.5"', modes: '8 color', output: 'AV to TV' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} magnifiers. Catalog now ${p.length} products.`);
