import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'furniture-bed-risers', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'utopia-bed-risers', name: 'Utopia Bedding Stackable Bed Risers (Set of 4)', brand: 'Utopia Bedding', sub: 'stackable', q: 'Utopia Bedding bed risers 3 5 inch stackable furniture 1300 lb', badge: 'Best Overall', price: 18.99, rating: 4.5, reviews: 42956, desc: 'The most-reviewed riser set — stack the 3" and 5" pieces for a 3", 5", or 8" lift, with a recessed cup that grips the furniture leg and a wide floor-protecting base.', features: ['Stackable 3" / 5" / 8" heights', '1,300 lb capacity (set)', 'Recessed cup prevents slipping', 'Wide base protects floors'], pros: ['Hugely popular and proven', 'Three heights in one set', 'Fits beds, desks, sofas, chairs'], cons: ['Black only'], bestFor: ['raising a bed for easier transfers', 'sofas & chairs', 'renters'], specs: { heights: '3/5/8"', capacity: '1300 lb', pack: '4', base: 'Wide non-slip' } }),
  mk({ id: 'kings-brand-6in-risers', name: 'Kings Brand 6-Inch Heavy-Duty Furniture Risers (Set of 4)', brand: 'Kings Brand', sub: 'fixed', q: 'Kings Brand furniture bed risers 6 inch heavy duty non slip set of 4', badge: 'Best 6-Inch', price: 17.99, rating: 4.6, reviews: 5147, desc: 'A sturdy fixed 6-inch lift in heavy-duty plastic with a non-slip bottom and a steady base that resists shaking — compatible with beds, desks, and sofas.', features: ['Fixed 6-inch height', 'Heavy-duty plastic, steady base', 'Non-slip bottom', 'Protects carpet and hardwood'], pros: ['Solid, no-wobble lift', 'Highly rated', 'Good value'], cons: ['Single fixed height'], bestFor: ['a consistent 6" lift', 'beds & sofas', 'standing more easily'], specs: { height: '6"', pack: '4', base: 'Non-slip', material: 'Heavy plastic' } }),
  mk({ id: 'annkut-8in-risers', name: 'ANNKUT 8-Inch Heavy-Duty Bed Risers (Set of 4)', brand: 'ANNKUT', sub: 'heavy-duty', q: 'ANNKUT bed risers 8 inch heavy duty L shape trapezoidal base 5000 lb', badge: 'Best Heavy-Duty', price: 32.98, rating: 4.7, reviews: 1211, desc: 'The highest-rated riser here — an 8-inch lift rated to 5,000 lb (set), with an L-shaped half-wrap edge and a trapezoidal anti-tip base, fitting legs up to 5.2".', features: ['8-inch height, 5,000 lb (set)', 'L-shaped half-wrap edge', 'Trapezoidal anti-tip base', 'TPU rubber floor protection'], pros: ['Very stable, anti-tip', 'Great for wheelchair-height beds', 'Top rating'], cons: ['Fixed 8" height'], bestFor: ['wheelchair-to-bed transfers', 'under-bed storage', 'heavier frames'], specs: { height: '8"', capacity: '5000 lb', fits: 'Legs to 5.2"', base: 'Trapezoidal' } }),
  mk({ id: 'home-it-bed-risers', name: 'Home It Adjustable Bed Risers (8-Piece Set)', brand: 'Home It', sub: 'stackable', q: 'Home It adjustable bed risers 3 5 8 inch 8 piece set 1300 lb', badge: 'Best 8-Piece Set', price: 20.99, rating: 4.5, reviews: 20087, desc: 'An 8-piece set (4 small + 4 large) that stacks to 3", 5", or 8", with raised edges that lock furniture legs in place — fits twin through California king.', features: ['8 pieces (4 small + 4 large)', 'Stackable 3" / 5" / 8"', '1,300 lb capacity', 'Raised edges grip legs'], pros: ['Most flexible heights', 'Fits any bed size', 'Secure leg cups'], cons: ['More pieces to manage'], bestFor: ['choosing the exact height', 'all bed sizes', 'sofas & desks'], specs: { heights: '3/5/8"', capacity: '1300 lb', pieces: '8', edges: 'Raised' } }),
  mk({ id: 'yookwutar-heavy-duty-risers', name: 'Yookwutar Heavy-Duty Furniture Risers (Set of 4)', brand: 'Yookwutar', sub: 'heavy-duty', q: 'Yookwutar bed risers heavy duty L shaped lip 6000 lb furniture', badge: 'Highest Capacity', price: 16.03, rating: 4.5, reviews: 1452, desc: 'Available in 2"–8" heights with the highest per-riser rating here (6,000 lb), an L-shaped lip that fits square, round, or irregular legs, and a TPU non-slip bottom.', features: ['Heights 2"/3"/4"/6"/8"', '6,000 lb per riser', 'L-shaped lip fits any leg', 'TPU rubber non-slip bottom'], pros: ['Enormous weight capacity', 'Fits irregular legs', 'Multiple heights'], cons: ['Choose height at purchase'], bestFor: ['bariatric / reinforced beds', 'heavy furniture', 'robot-vacuum clearance'], specs: { heights: '2–8"', capacity: '6000 lb/riser', lip: 'L-shaped', base: 'TPU' } }),
  mk({ id: 'bee-neat-usb-bed-riser', name: 'Bee Neat 7.25" Bed Risers with USB & Power Outlets (Set of 4)', brand: 'Bee Neat', sub: 'usb-power', q: 'Bee Neat bed riser USB power outlet 7.25 inch charging set of 4', badge: 'Best with Charging', price: 39.99, rating: 4.5, reviews: 1648, desc: 'A 7.25" riser set where one riser adds 2 fast USB ports, 2 USB-C adapters, and 2 AC outlets on a 6-ft cord — keeping a phone, CPAP remote, or hearing-aid charger within reach.', features: ['7.25" lift, 1,400 lb (set)', '2 USB + 2 USB-C + 2 AC on one riser', '6-ft power cord', '3 standard risers + 1 power riser'], pros: ['Charging within arm’s reach of bed', 'Good lift height', 'No cords across the floor'], cons: ['Pricier than plain risers'], bestFor: ['bedside charging', 'CPAP / hearing aids', 'phones & tablets'], specs: { height: '7.25"', capacity: '1400 lb', ports: '2 USB + 2 USB-C + 2 AC', cord: '6 ft' } }),
  mk({ id: 'simplify-6in-bed-riser', name: 'Simplify 6-Inch Silicone Non-Slip Bed Riser (Set of 4)', brand: 'Simplify', sub: 'fixed', q: 'Simplify 6 inch bed riser silicone non slip wheel caster groove set of 4', badge: 'Best for Caster Beds', price: 14.99, rating: 4.5, reviews: 550, desc: 'A fixed 6-inch riser with a patented wheel-caster groove and a silicone non-slip bottom that works on carpet and hardwood — handy for acid-reflux or back-pain bed elevation.', features: ['Fixed 6" height', 'Patented wheel-caster groove', 'Silicone non-slip bottom', 'Works on carpet & hardwood'], pros: ['Holds caster-wheel beds securely', 'Grippy on any floor', 'Lowest price'], cons: ['Fewer reviews'], bestFor: ['beds with caster wheels', 'acid reflux elevation', 'a simple 6" lift'], specs: { height: '6"', grip: 'Silicone', feature: 'Caster groove', pack: '4' } }),
  mk({ id: 'cgk-bed-risers', name: 'CGK Unlimited Stackable Bed Risers (8-Pack)', brand: 'CGK Unlimited', sub: 'stackable', q: 'CGK Unlimited bed risers 3 5 inch stackable 8 pack 1300 lb recessed', badge: 'Best 8-Pack Combo', price: 18.99, rating: 4.6, reviews: 79, desc: 'An 8-pack combo (4×3" + 4×5") that stacks to 8", with a recessed cup design and wide base that work on hardwood, tile, and carpet — flexible value.', features: ['8-pack (4×3" + 4×5")', 'Stackable to 8"', '1,300 lb capacity', 'Recessed cup, wide base'], pros: ['Mix heights as needed', 'Works on any floor', 'Good value'], cons: ['Newer listing, fewer reviews'], bestFor: ['custom heights', 'beds & furniture', 'value'], specs: { heights: '3/5/8"', capacity: '1300 lb', pieces: '8', base: 'Wide' } }),
  mk({ id: 'spacelead-bed-step-stool', name: 'SPACELEAD Adjustable Mobility Step Stool for Seniors', brand: 'SPACELEAD', sub: 'step-stool', q: 'SPACELEAD mobility step stool adults seniors adjustable height 600 lb anti slip', badge: 'Best Bed Step Stool', price: 26.99, rating: 4.7, reviews: 1331, desc: 'A height-adjustable step stool (up to 15.36") rated to 600 lb with five anti-slip feet and a detachable washable mat — ideal for safely getting in and out of a raised bed.', features: ['600 lb capacity', 'Adjustable height to 15.36"', '5 anti-slip feet', 'Detachable washable rubber mat'], pros: ['Very high weight capacity', 'Adjusts to bed height', 'Stable, anti-slip'], cons: ['A step, not a riser'], bestFor: ['getting into a raised bed', 'high beds & RVs', 'safe stepping up'], specs: { capacity: '600 lb', height: 'To 15.36"', feet: '5 anti-slip', mat: 'Washable' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} furniture-bed-risers. Catalog now ${p.length} products.`);
