import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'stair-safety', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'cosy-homeer-carpet-stair-treads', name: 'COSY HOMEER Carpet Stair Treads (15-Pack)', brand: 'COSY HOMEER', sub: 'carpet-treads', q: 'COSY HOMEER carpet stair treads non slip 15 pack', badge: 'Best Overall', price: 76.49, rating: 4.7, reviews: 8211, desc: 'The highest-rated indoor carpet treads we found — fluffy, soft underfoot, with a grippy TPE backing that survives 30+ washes.', features: ['Fluffy water-resistant polyester', 'Non-slip TPE backing (holds 30+ washes)', 'Peel & stick, no sticky residue', 'Fade- and shed-resistant, 28"×9"'], pros: ['Soft and quiet underfoot', 'Strong, residue-free grip', 'Holds up to washing'], cons: ['Priciest set in our roundup'], bestFor: ['indoor wooden stairs', 'noise reduction', 'homes with pets'], specs: { type: 'Carpet tread', size: '28×9 in', pack: '15', backing: 'TPE non-slip' } }),
  mk({ id: 'mbigm-carpet-stair-treads', name: 'MBIGM Non-Slip Carpet Stair Treads (15-Pack)', brand: 'MBIGM', sub: 'carpet-treads', q: 'MBIGM non slip carpet stair treads 15 pack', badge: 'Best Value', price: 41.99, rating: 4.6, reviews: 8566, desc: 'Our best-value carpet tread: a 3-layer build with a TPU non-skid bottom, machine washable, and cuttable to fit your stairs.', features: ['3-layer construction + TPU non-skid base', 'Machine washable, water-resistant', 'Can be cut to fit', '8"×30" standard tread'], pros: ['Excellent price per tread', 'Most-reviewed set we found', 'Trimmable for odd stairs'], cons: ['Thinner pile than premium picks'], bestFor: ['indoor stairs', 'budget whole-staircase coverage', 'easy cleaning'], specs: { type: 'Carpet tread', size: '8×30 in', pack: '15', backing: 'TPU non-skid' } }),
  mk({ id: 'kooteta-carpet-stair-treads', name: 'KOOTETA Non-Slip Carpet Stair Treads (15-Pack)', brand: 'KOOTETA', sub: 'carpet-treads', q: 'KOOTETA non slip carpet stair treads waterproof 15 pack', badge: 'Best for Quiet', price: 39.98, rating: 4.6, reviews: 3241, desc: 'High-pile, waterproof treads with a self-adhesive TPR backing that adds noise and thermal insulation on hard stairs.', features: ['High-pile soft polyester', 'Waterproof self-adhesive TPR backing', 'Noise + thermal insulation', 'Fits wood, tile, marble; machine washable'], pros: ['Plush and warm underfoot', 'Cuts stair noise noticeably', 'Sticks to many surfaces'], cons: ['Adhesive is single-use once placed'], bestFor: ['quiet nighttime trips', 'hard tile/marble stairs', 'comfort'], specs: { type: 'Carpet tread', size: '8×30 in', pack: '15', backing: 'TPR adhesive' } }),
  mk({ id: 'tranquilmoments-stair-treads', name: 'TranquilMoments Non-Slip Stair Treads (15-Pack)', brand: 'TranquilMoments', sub: 'carpet-treads', q: 'TranquilMoments non slip stair treads reusable 15 pack', badge: 'Best No-Adhesive', price: 29.99, rating: 4.5, reviews: 370, desc: 'A reusable TPE backing that grips without any adhesive — repositionable, stain-resistant, and cuttable for irregular stairs.', features: ['100% PET polyester', 'Reusable TPE backing (no adhesive)', 'Stain-resistant, noise-reducing', 'Cuttable for irregular stairs'], pros: ['Repositionable, leaves no residue', 'Lowest price in the roundup', 'Good for rentals'], cons: ['Fewer reviews than top picks'], bestFor: ['renters', 'repositioning', 'irregular stairs'], specs: { type: 'Carpet tread', size: '8×30 in', pack: '15', backing: 'Reusable TPE' } }),
  mk({ id: 'ottomanson-rubber-stair-treads', name: 'Ottomanson Outdoor Rubber Stair Treads (5-Pack)', brand: 'Ottomanson', sub: 'rubber-treads', q: 'Ottomanson outdoor rubber stair treads waterproof 5 pack', badge: 'Best Outdoor', price: 31.54, rating: 4.6, reviews: 2394, desc: 'Heavy-duty waterproof rubber treads built for porches, decks, and concrete steps — they shrug off rain, snow, and ice.', features: ['Heavy-duty waterproof rubber', 'Weatherproof: rain, snow, ice', 'Best grip on concrete/brick/stone', 'Hose-clean, 10"×30"'], pros: ['True all-weather grip', 'Easy to rinse clean', 'Decorative scroll design'], cons: ['Not soft like carpet treads'], bestFor: ['outdoor steps', 'porches and decks', 'concrete/brick stairs'], specs: { type: 'Rubber tread', size: '10×30 in', pack: '5', use: 'Outdoor/all-weather' } }),
  mk({ id: 'metty-2step-stair-handrail', name: 'Metty Metal Adjustable 2-Step Stair Handrail', brand: 'Metty', sub: 'handrail', q: 'Metty metal adjustable stair handrail wrought iron 1-5 steps', badge: 'Most Versatile', price: 47.99, rating: 4.5, reviews: 3134, desc: 'A wrought-iron handrail rated to 600 lb with an adjustable 0–45° angle that fits 1–5 steps without cutting — installs with the included kit.', features: ['600 lb capacity wrought iron', 'Adjustable angle 0°–45° (fits 1–5 steps)', 'Anti-rust painted finish', 'Complete installation kit included'], pros: ['Fits most short staircases', 'Very strong and stable', 'No cutting required'], cons: ['Requires drilling to mount'], bestFor: ['front steps', 'indoor or outdoor stairs', '1–5 step runs'], specs: { type: 'Handrail', capacity: '600 lb', steps: '1–5', mount: 'Wall/post, drilled' } }),
  mk({ id: 'sahans-ushape-grab-rail', name: 'Sahans U-Shape 16" Wall-Mount Grab Rail', brand: 'Sahans', sub: 'handrail', q: 'Sahans U-shape wall mount stair grab rail handrail 16 inch', badge: 'Best Grab Rail', price: 27.99, rating: 4.8, reviews: 284, desc: 'A smooth U-shaped grab rail in powder-coated steel for the 1–3 entry steps at a door, porch, or garage — the highest-rated handrail we found.', features: ['Smooth U-shaped grip', 'Heavy-duty powder-coated steel', 'Indoor/outdoor (porch, garage)', '6 screws + expansion tubes included'], pros: ['Highest rating in the roundup', 'Comfortable, secure grip', 'Quick to install'], cons: ['Best for short 1–3 step runs'], bestFor: ['entry steps', 'doorways', 'garage/porch'], specs: { type: 'Grab rail', size: '16 in', steps: '1–3', finish: 'Powder-coated' } }),
  mk({ id: 'sahans-heavy-duty-grab-rail', name: 'Sahans Heavy Duty 16" Wall-Mount Grab Rail', brand: 'Sahans', sub: 'handrail', q: 'Sahans heavy duty wall mount grab rail 600 lb 16 inch', badge: 'Strongest Grab Rail', price: 21.99, rating: 4.7, reviews: 305, desc: 'A 16-gauge steel grab rail with a 600 lb pull rating and a two-level U-grip — a budget-friendly, rock-solid handhold for 1–2 steps.', features: ['600 lb max pull force', '2-level U-shape grip', '1.2" dia. 16-gauge steel', 'Rust-protective powder coat, full hardware'], pros: ['Very strong for the price', 'Two grip heights', 'Rust-resistant'], cons: ['Short rail (1–2 steps)'], bestFor: ['entry steps', 'extra-strong handhold', 'budget installs'], specs: { type: 'Grab rail', size: '16 in', capacity: '600 lb', steps: '1–2' } }),
  mk({ id: 'lukloy-stair-balusters', name: 'LukLoy Freestanding U-Shape Stair Balusters (6-Pack)', brand: 'LukLoy', sub: 'stair-rail-kit', q: 'LukLoy freestanding U-shape stair balusters railing kit', badge: 'Best Freestanding Kit', price: 144.99, rating: 4.6, reviews: 52, desc: 'A no-wall-needed railing kit: modern 36" iron balusters with an adjustable top plate for floor or stair mounting that passes the 4-inch ball safety test.', features: ['Modern U-shaped iron balusters, 36"', 'Adjustable plate: floor or stair mount', 'Passes 4-inch ball safety test', 'Matte black corrosion-resistant coat'], pros: ['No wall required', 'Code-style 4-inch spacing', 'Sturdy and modern'], cons: ['Most involved installation', 'Higher price'], bestFor: ['open staircases', 'no wall to mount to', 'full railing runs'], specs: { type: 'Railing kit', height: '36 in', pack: '6', mount: 'Floor or stair' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} stair-safety. Catalog now ${p.length} products.`);
