import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'hearing-amplifiers', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'williams-pocketalker-amplifier', name: 'Williams Sound Pocketalker Ultra (Duo Pack)', brand: 'Williams Sound', sub: 'pocket', q: 'Williams Sound Pocketalker Ultra personal amplifier duo', badge: 'Best Overall', price: 202.00, rating: 4.4, reviews: 2100, desc: 'The 50-year industry gold standard: a simple body-worn amplifier with a big volume knob, 200-hour battery, and a 12-ft TV cord — no tiny buttons.', features: ['Adjustable volume + tone', '200-hr AAA battery life', 'Earbud + folding headphone', '12-ft TV listening cord, 5-yr warranty'], pros: ['Dead-simple big-knob controls', 'Extremely long battery life', 'Trusted, durable, well-supported'], cons: ['Worn on the body with a cord'], bestFor: ['TV and one-on-one talk', 'people who struggle with tiny buttons', 'reliability'], specs: { type: 'Body-worn (PSAP)', battery: '200 hr', controls: 'Volume + tone', warranty: '5 yr' } }),
  mk({ id: '3fp-invisible-amplifier', name: '3FP Rechargeable Invisible In-Ear Amplifier', brand: '3FP', sub: 'in-ear', q: '3FP rechargeable digital invisible in ear hearing amplifier', badge: 'Best Discreet', price: 79.99, rating: 4.7, reviews: 581, desc: 'The highest-rated pick here: a nearly invisible in-ear rechargeable amplifier with 2-channel sound and noise cancellation for clear, discreet daily wear.', features: ['Invisible in-ear design', '2-channel digital sound', 'Noise cancellation', 'Rechargeable'], pros: ['Highest rating in the roundup', 'Very discreet', 'Clear sound quality'], cons: ['In-ear fit not for everyone'], bestFor: ['discreet everyday wear', 'mild amplification', 'conversations'], specs: { type: 'In-ear (PSAP)', channels: '2', power: 'Rechargeable', noise: 'Cancellation' } }),
  mk({ id: 'earcentric-easycharge-amplifier', name: 'EarCentric EasyCharge Rechargeable Pair', brand: 'EarCentric', sub: 'bte', q: 'EarCentric EasyCharge rechargeable hearing amplifiers pair BTE', badge: 'Best BTE Pair', price: 149.00, rating: 4.2, reviews: 5200, desc: 'A USA-engineered behind-the-ear pair with 20+ hours per 3-hour charge, noise reduction, and a dual charging dock — the most-reviewed amplifier here.', features: ['USA-engineered digital core', '20+ hr battery per 3-hr charge', 'Nearly invisible BTE', 'Dual charging dock'], pros: ['Comes as a pair', 'All-day battery', 'Strong review base'], cons: ['BTE tube visible up close'], bestFor: ['both ears', 'mild-moderate loss', 'all-day wear'], specs: { type: 'Behind-the-ear (PSAP)', battery: '20+ hr', count: 'Pair', power: 'Rechargeable' } }),
  mk({ id: 'superear-se7500-amplifier', name: 'SuperEar SE7500 Personal Sound Amplifier', brand: 'SuperEar', sub: 'pocket', q: 'SuperEar SE7500 personal sound amplifier directional mic', badge: 'Best for TV & Events', price: 77.95, rating: 4.1, reviews: 1300, desc: 'A body-worn amplifier with 50 dB of gain and a directional mic — great for TV, lectures, worship, and birdwatching, with included earbuds and stereo headphones.', features: ['50 dB ambient gain', 'Directional microphone', '80-hr battery, belt clip', 'Earbuds + stereo headphones'], pros: ['Strong, clear amplification', 'Directional mic focuses ahead', 'Long battery life'], cons: ['Body-worn with a cord'], bestFor: ['TV and lectures', 'worship services', 'outdoor listening'], specs: { type: 'Body-worn (PSAP)', gain: '50 dB', battery: '80 hr', mic: 'Directional' } }),
  mk({ id: 'iroger-rechargeable-amplifier', name: 'IROGER Rechargeable Hearing Amplifier (PSAP)', brand: 'IROGER', sub: 'bte', q: 'IROGER rechargeable hearing amplifier PSAP directional noise canceling', badge: 'Longest Battery', price: 99.00, rating: 4.0, reviews: 244, desc: 'A behind-the-ear amplifier with up to 65 dB gain, a directional noise-canceling mic, automatic gain control, and an exceptional 120-hour battery life.', features: ['Up to 65 dB gain', 'Directional noise-canceling mic', 'Automatic gain control', '120-hr battery, one-knob control'], pros: ['Very long battery life', 'Simple one-knob operation', 'Auto gain control'], cons: ['Single device, not a pair'], bestFor: ['simple controls', 'long battery life', 'mild-moderate loss'], specs: { type: 'Behind-the-ear (PSAP)', gain: '65 dB', battery: '120 hr', controls: 'One-knob' } }),
  mk({ id: 'manzelun-bte-amplifier', name: 'Manzelun Rechargeable BTE Amplifier (Noise Cancelling)', brand: 'Manzelun', sub: 'bte', q: 'Manzelun rechargeable BTE hearing amplifier noise cancelling lightweight', badge: 'Best Budget', price: 35.89, rating: 4.1, reviews: 492, desc: 'An ultra-light 5.5 g behind-the-ear amplifier with double noise cancellation, a 25-hour battery, and both a physical slider and volume knob — easy for seniors.', features: ['Ultra-light 5.5 g', 'Double noise cancellation', '25-hr battery, charging case', 'Physical slider + volume knob'], pros: ['Lowest price here', 'Barely felt at 5.5 g', 'Tactile controls'], cons: ['Smaller battery than premium picks'], bestFor: ['budget buyers', 'lightweight comfort', 'simple controls'], specs: { type: 'Behind-the-ear (PSAP)', weight: '5.5 g', battery: '25 hr', noise: 'Double cancel' } }),
  mk({ id: 'nurdhong-bte-amplifier', name: 'NurdHong Rechargeable BTE Amplifier (German Chip)', brand: 'NurdHong', sub: 'bte', q: 'NurdHong rechargeable BTE hearing amplifier German digital chip', badge: 'Most Adjustable', price: 39.99, rating: 4.0, reviews: 453, desc: 'A behind-the-ear amplifier with a German DSP chip, three frequency modes, four volume levels, and a 48-hour battery — and it works comfortably with glasses.', features: ['German DSP noise-reduction chip', '3 frequency modes, 4 volume levels', '48-hr battery', 'Works with glasses'], pros: ['Lots of adjustment', 'Good battery life', 'Glasses-friendly fit'], cons: ['Single device, not a pair'], bestFor: ['fine-tuning the sound', 'glasses wearers', 'budget buyers'], specs: { type: 'Behind-the-ear (PSAP)', modes: '3 frequency', battery: '48 hr', chip: 'German DSP' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} hearing-amplifiers. Catalog now ${p.length} products.`);
