import fs from 'node:fs';
const f = 'data/products.json';
const p = JSON.parse(fs.readFileSync(f, 'utf8'));
const mk = (o) => ({
  id: o.id, name: o.name, brand: o.brand, category: 'daylight-task-lamps', subCategory: o.sub,
  amazonUrl: `https://www.amazon.com/s?k=${encodeURIComponent(o.q)}&tag=seniorsaferhome-20`,
  asin: '', editorialImageFallback: `/images/products/${o.id}.svg`,
  shortDescription: o.desc, badge: o.badge, price: o.price, priceCurrency: 'USD',
  rating: o.rating, ...(o.reviews ? { reviewCount: o.reviews } : {}),
  features: o.features, pros: o.pros || o.features.slice(0, 2), cons: o.cons || [], bestFor: o.bestFor || [],
  specs: o.specs, reviewSlug: null, lastManualReview: '2026-06-14',
});
const add = [
  mk({ id: 'lepro-task-lamp', name: 'Lepro LED Desk Lamp (Forbes Vetted)', brand: 'Lepro', sub: 'desk-lamp', q: 'Lepro LED desk lamp 800lm 5 color modes flexible arm memory', badge: 'Best Overall', price: 26.99, rating: 4.7, reviews: 8043, desc: "A Forbes-vetted task lamp with 800 lumens, 5 color modes × 5 brightness levels, a flexible arm, a memory function, and flicker-free light — versatile for reading and crafts.", features: ['800 lumens, 9.5W', '5 color modes × 5 brightness', 'Flexible arm + memory function', 'Non-flickering, 2-yr warranty'], pros: ['Bright and adjustable', 'Flicker-free (easy on eyes)', 'Great value'], cons: ['Desk-only (no floor option)'], bestFor: ['reading & crafts', 'low-vision desk work', 'bedside table'], specs: { lumens: '800', modes: '5 color × 5', arm: 'Flexible', warranty: '2 yr' } }),
  mk({ id: 'ottlite-softtouch-desk-lamp', name: 'OttLite Soft Touch LED Desk Lamp (Natural Daylight)', brand: 'OttLite', sub: 'desk-lamp', q: 'OttLite soft touch LED desk lamp 5000K natural daylight flexible neck low vision', badge: 'Best for Low Vision', price: 49.99, rating: 4.8, reviews: 1136, desc: 'A 5000K natural-daylight lamp from the brand founded by a photobiologist — clinically designed to reduce eye strain, with 3 brightness levels and a flexible 8–18" neck.', features: ['5000K natural daylight LED', '3 brightness levels, touch control', 'Flexible neck 8–18"', '40,000-hour LED'], pros: ['Trusted low-vision brand', 'Reduces eye strain', 'Highly rated'], cons: ['Pricier than basic lamps'], bestFor: ['macular degeneration / low vision', 'long reading sessions', 'detail work'], specs: { color: '5000K', cri: 'High', neck: '8–18"', brightness: '3' } }),
  mk({ id: 'ottlite-creativecurves-desk-lamp', name: 'OttLite Creative Curves LED Desk Lamp', brand: 'OttLite', sub: 'desk-lamp', q: 'OttLite Creative Curves LED desk lamp 5000K natural daylight adjustable neck 20 inch', badge: 'Best Adjustable Neck', price: 49.99, rating: 4.7, reviews: 2222, desc: 'A 5000K natural-daylight lamp with a 20" extending neck for precise positioning, 4 brightness levels, touch controls, and superior color rendering.', features: ['5000K natural daylight', '4 brightness levels, touch controls', 'Extends 20" for positioning', 'Energy-efficient LED'], pros: ['Long reach for precise light', 'Daylight color accuracy', 'Easy touch control'], cons: ['Desk lamp only'], bestFor: ['needlework & hobbies', 'aiming light precisely', 'low-vision reading'], specs: { color: '5000K', neck: '20" reach', brightness: '4', control: 'Touch' } }),
  mk({ id: 'lepower-rg0-desk-lamp', name: 'LEPOWER 12W Eye-Safe LED Desk Lamp (RG0)', brand: 'LEPOWER', sub: 'desk-lamp', q: 'LEPOWER 12W desk lamp 800lm RG0 certified blue light free gooseneck wide panel', badge: 'Best Eye-Safe', price: 26.98, rating: 4.7, reviews: 2848, desc: 'RG0-certified (100% blue-light-hazard free) with 800 lumens, 50 lighting modes, a 360° gooseneck, and a 50" wide coverage panel — ideal after cataract surgery or for glare sensitivity.', features: ['RG0 certified (no blue-light hazard)', '800 lumens, 50 lighting modes', '360° gooseneck', '50" wide coverage panel'], pros: ['Safest for sensitive eyes', 'Wide, even light', 'Many modes, great value'], cons: ['Desk-only'], bestFor: ['post-cataract surgery', 'glare sensitivity', 'wide desk coverage'], specs: { lumens: '800', safety: 'RG0', arm: '360° gooseneck', modes: '50' } }),
  mk({ id: 'marctronic-floor-lamp', name: 'marctronic 1800lm LED Floor Lamp (Remote)', brand: 'marctronic', sub: 'floor-lamp', q: 'marctronic 18W 1800lm LED floor lamp daylight remote dimming gooseneck', badge: 'Best Value Floor Lamp', price: 29.98, rating: 4.7, reviews: 3104, desc: 'A bright 1800-lumen floor lamp with 4 color temperatures, stepless 5–100% dimming, a 50-ft remote (great for arthritis), a 360° gooseneck, and a 5-year warranty.', features: ['18W / 1800 lumens', '4 color temps (2700–6500K)', 'Stepless dimming + 50-ft remote', '360° gooseneck, 5-yr warranty'], pros: ['Remote (no reaching)', 'Very bright and adjustable', 'Long warranty'], cons: ['Floor footprint'], bestFor: ['reading chairs / recliners', 'arthritis (remote)', 'no table needed'], specs: { lumens: '1800', temps: '2700–6500K', remote: '50 ft', warranty: '5 yr' } }),
  mk({ id: 'brightech-litespan-floor-lamp', name: 'Brightech Litespan LED Floor Lamp (Daylight)', brand: 'Brightech', sub: 'floor-lamp', q: 'Brightech Litespan LED floor lamp 6000K daylight gooseneck reading crafts', badge: 'Best Daylight Floor Lamp', price: 54.99, rating: 4.6, reviews: 20531, desc: 'A pure 6000K cool-daylight floor lamp ideal for detail work, with a flexible 42–53" gooseneck, a touch switch, and a head that stays cool to the touch — heavily reviewed.', features: ['6000K cool daylight, 950 lumens', 'Flexible gooseneck 42–53"', 'Touch switch, stays cool', '3-year warranty'], pros: ['Crisp daylight for detail', 'Aims over the shoulder', 'Most-reviewed floor lamp here'], cons: ['Single color temperature'], bestFor: ['crafts & reading', 'over-chair lighting', 'detail work'], specs: { color: '6000K', lumens: '950', neck: '42–53"', control: 'Touch' } }),
  mk({ id: 'yikuneng-floor-lamp', name: 'Yikuneng 1800lm LED Floor Lamp (Reading Mode)', brand: 'Yikuneng', sub: 'floor-lamp', q: 'Yikuneng 18W 1800lm LED floor lamp dimmable reading mode RF remote presets', badge: 'Best Reading Mode', price: 29.99, rating: 4.7, reviews: 813, desc: 'An 1800-lumen floor lamp with stepless dimming, a 50-ft RF remote, and six preset modes including dedicated Reading and gentle Nursing modes for nighttime checks.', features: ['18W / 1800 lumens, 2700–6500K', 'Stepless 5–100% dimming', '6 presets (Reading/Working/Night/Nursing)', '50-ft RF remote, memory'], pros: ['Dedicated reading & nursing modes', 'Remote control', 'Very bright'], cons: ['Fewer reviews'], bestFor: ['reading chairs', 'nighttime caregiving', 'dementia-friendly soft light'], specs: { lumens: '1800', presets: '6', remote: 'RF 50 ft', dimming: 'Stepless' } }),
  mk({ id: 'ottlite-clearsun-floor-lamp', name: 'OttLite ClearSun LED Floor Lamp (95+ CRI)', brand: 'OttLite', sub: 'floor-lamp', q: 'OttLite ClearSun LED floor lamp 5000K 95 CRI adjustable height weighted base', badge: 'Best Premium Floor Lamp', price: 139.99, rating: 4.8, reviews: 363, desc: 'A premium 5000K floor lamp with 95+ CRI ClearSun LEDs for true color, an adjustable 47.5–64" height, touch controls, and a weighted base — excellent over a reading chair.', features: ['ClearSun LED, 95+ CRI, 5000K', '3 brightness levels', 'Adjustable height 47.5–64"', 'Touch controls, weighted base'], pros: ['Exceptional color accuracy', 'Stable weighted base', 'Trusted low-vision brand'], cons: ['Premium price'], bestFor: ['over-chair reading', 'low vision', 'true-color crafts'], specs: { color: '5000K', cri: '95+', height: '47.5–64"', base: 'Weighted' } }),
  mk({ id: 'verilux-happylight-duo-lamp', name: 'Verilux HappyLight Duo Light-Therapy & Task Lamp', brand: 'Verilux', sub: 'light-therapy', q: 'Verilux HappyLight Duo 2 in 1 light therapy task lamp 10000 lux UV free', badge: 'Best Light Therapy', price: 79.00, rating: 4.6, reviews: 539, desc: 'A 2-in-1 lamp delivering 10,000 lux UV-free full-spectrum light therapy and doubling as a task reading lamp — 7 brightness and 3 color settings, with a 360° gooseneck.', features: ['10,000 lux UV-free light therapy', '7 brightness + 3 color temps', '360° gooseneck, USB charging port', 'Clinically reduces eye strain'], pros: ['Therapy + reading in one', 'Helps winter low mood', 'Flexible positioning'], cons: ['Smaller task footprint'], bestFor: ['winter blues + low vision', 'energy/mood boost', 'desk reading'], specs: { lux: '10000', uv: 'Free', brightness: '7', temps: '3' } }),
  mk({ id: 'daylight-slimline4-lamp', name: 'Daylight Company Slimline 4 LED Table Lamp (95+ CRI)', brand: 'Daylight Company', sub: 'desk-lamp', q: 'Daylight Company Slimline 4 LED table lamp 6000K 95 CRI anti glare clamp', badge: 'Best for Crafts', price: 223.99, rating: 4.6, reviews: 1748, desc: 'A professional-grade 6000K / 3,200-lux lamp with 95+ CRI and an anti-glare diffuser that reveals true thread, fabric, and paint colors — with a USB-C port and clamp or screw mount.', features: ['6000K, 3,200 lux, 95+ CRI', 'Anti-glare diffuser', '4 brightness levels, USB-C', 'Table clamp or screw mount'], pros: ['Studio-grade color accuracy', 'Glare-free bright light', 'Clamp saves desk space'], cons: ['Most expensive lamp here'], bestFor: ['needlepoint & embroidery', 'true-color detail work', 'serious crafters'], specs: { color: '6000K', lux: '3200', cri: '95+', mount: 'Clamp/screw' } }),
];
const ids = new Set(p.map((x) => x.id));
const fresh = add.filter((x) => !ids.has(x.id));
p.push(...fresh);
fs.writeFileSync(f, JSON.stringify(p, null, 2) + '\n');
console.log(`Added ${fresh.length} daylight-task-lamps. Catalog now ${p.length} products.`);
